"""edit role-rights fields

Revision ID: 03f287393ac1
Revises: 5d14e770fb59
Create Date: 2025-12-30 00:53:51.615515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f287393ac1'
down_revision: Union[str, Sequence[str], None] = '5d14e770fb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_rights', sa.Column('read_posts_access', sa.Boolean(), nullable=True))
    op.add_column('role_rights', sa.Column('write_posts_access', sa.Boolean(), nullable=True))
    op.add_column('role_rights', sa.Column('delete_posts_access', sa.Boolean(), nullable=True))
    op.add_column('role_rights', sa.Column('manage_roles_access', sa.Boolean(), nullable=True))
    op.drop_column('role_rights', 'write_access')
    op.drop_column('role_rights', 'delete_access')
    op.drop_column('role_rights', 'read_access')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_rights', sa.Column('read_access', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('role_rights', sa.Column('delete_access', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('role_rights', sa.Column('write_access', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('role_rights', 'manage_roles_access')
    op.drop_column('role_rights', 'delete_posts_access')
    op.drop_column('role_rights', 'write_posts_access')
    op.drop_column('role_rights', 'read_posts_access')
    # ### end Alembic commands ###
