"""create relationship between user, role, role_rights, post

Revision ID: 5d14e770fb59
Revises: a5b3a33f6ce2
Create Date: 2025-12-29 23:52:48.981738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d14e770fb59'
down_revision: Union[str, Sequence[str], None] = 'a5b3a33f6ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'])
    op.add_column('role', sa.Column('rights_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'role', 'role_rights', ['rights_id'], ['id'])
    op.add_column('role_rights', sa.Column('role_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'role_rights', 'role', ['role_id'], ['id'])
    op.add_column('user', sa.Column('role_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_constraint(None, 'role_rights', type_='foreignkey')
    op.drop_column('role_rights', 'role_id')
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'rights_id')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'author_id')
    # ### end Alembic commands ###
