"""remove role_rights, add fields in role

Revision ID: 7f0341119b61
Revises: 03f287393ac1
Create Date: 2025-12-30 02:14:48.466509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0341119b61'
down_revision: Union[str, Sequence[str], None] = '03f287393ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('role_rights_id_fkey'), 'role', type_='foreignkey')
    op.drop_column('role', 'rights_id')
    op.drop_table('role_rights')
    op.add_column('role', sa.Column('read_posts_access', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('write_posts_access', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('delete_posts_access', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('manage_roles_access', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('rights_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('role_rights_id_fkey'), 'role', 'role_rights', ['rights_id'], ['id'])
    op.drop_column('role', 'manage_roles_access')
    op.drop_column('role', 'delete_posts_access')
    op.drop_column('role', 'write_posts_access')
    op.drop_column('role', 'read_posts_access')
    op.create_table('role_rights',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('read_posts_access', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('write_posts_access', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('delete_posts_access', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('manage_roles_access', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('role_rights_role_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('role_rights_pkey'))
    )
    # ### end Alembic commands ###
